### ISSUE TITLE
Initialize New Tech Stack

### ISSUE THREAD

**Issue by kirklikecaptain** [kirklikecaptain/afistfulofvinyl#24]
# Tasks
- [x] Init Typescript Next.js boilerplate app
- [x] Add ESLint + Prettier
- [x] Add UI library
- [x] Add Contentful Client
- [x] Add Contentful API type generation
- [x] Add `.env.local` variables
